### ISSUE TITLE
Static member 'requestAccessWithCompletion' cannot be used on instance of type 'SwiftAddressBook'

### ISSUE THREAD

**Issue by genius50** [SocialbitGmbH/SwiftAddressBook#75]
I'm using the SwiftAddressBook like this,

    swiftAddressBook?.requestAccessWithCompletion({ (success, error) -> Void in
            if success {
                //do something with swiftAddressBook
            }
            else {
                //no success. Optionally evaluate error
            }
        })

And I'm getting this Error, 

Static member 'requestAccessWithCompletion' cannot be used on instance of type 'SwiftAddressBook'

Deployment Target : 8.0
Xcode : 7.2
Swift : 2.1.1

**Comment by salabaha** [comment]
You are getting this error because requestAccessWithCompletion is a class methods and you are trying to call it on instance of the class SwiftAddressBook. So what you want is to call this method on the class itself. See below working snippet of the code. 

```
SwiftAddressBook.requestAccessWithCompletion({ (success, error) -> Void in
        if success {
            //do something with swiftAddressBook
        }
        else {
            //no success. Optionally evaluate error
        }
    })
```
or

```
swiftAddressBook?.dynamicType.requestAccessWithCompletion({ (success, error) -> Void in
        if success {
            //do something with swiftAddressBook
        }
        else {
            //no success. Optionally evaluate error
        }
    })
```

**Comment by ejeklint** [comment]
Odd. This works perfectly fine for me:

```swift
import SwiftAddressBook

...

swiftAddressBook?.requestAccessWithCompletion {
            (accessGranted: Bool, _: CFError?) -> Void in
            
            if accessGranted {
                self.people = swiftAddressBook?.allPeople
                print("found \(self.people!.count) people in address book")
            } else {
                print("unauthorised for address book access")
            }
        }
```

I'm using version 0.5.0.

**Comment by TAKeanice** [comment]
The method was changed to be a class method in the most recent version. Before, only an inconsistency between the implementation and the documentation of ABAddressBook made the code work.

**Comment by TAKeanice** [comment]
I have updated the readme to reflect that change.

**Comment by ejeklint** [comment]
Thanks for the update on this. But the example code at cocoapods is still wrong then...

**Comment by TAKeanice** [comment]
That is strange... Are you at version 0.6.1?  In the repository, all occurrences are fixed.

**Comment by ejeklint** [comment]
Yes I'm on 0.6.1, it's just the documentation on CocoaPods that's not updated. Also, CocoaPods points to the wiki page HowTo which also looks un-updated. :)

**Comment by TAKeanice** [comment]
That's right :D I completely forgot about the howto pages... And the readme was also changed after the 0.6.1 release. It will be up to date after the next version got released! Meanwhile, the code in the example app should run correctly.
