### ISSUE TITLE
Crash when SwiftAddressBookPerson.phoneNumbers is set

### ISSUE THREAD

**Issue by albertbori** [SocialbitGmbH/SwiftAddressBook#9]
The following code crashes when you attempt to set the phone numbers:

    var phone = MultivalueEntry(value: testUser.contactMethod, label: "mobile", id: 1)
    person.phoneNumbers = [phone]

Stack Trace:

	Thread 1Queue : com.apple.main-thread (serial)
	#0	0x0000000103efe36a in ABMultiValueAddValueAndLabel ()
	#1	0x00000001030af3ad in MyApp.SwiftAddressBookPerson.(setMultivalueProperty in _301C513C9265CB051530A5ABCA777C60) (MyApp.SwiftAddressBookPerson)<A : Swift.AnyObject>(Swift.Int32, Swift.Optional<Swift.Array<MyApp.MultivalueEntry<A>>>) -> () at /Users/me/dev/myapp/MyApp/Utilities/SwiftAddressBookWrapper.swift:693
	#2	0x00000001030a9e6e in MyApp.SwiftAddressBookPerson.phoneNumbers.setter : Swift.Optional<Swift.Array<MyApp.MultivalueEntry<Swift.String>>> at /Users/me/dev/myapp/MyApp/Utilities/SwiftAddressBookWrapper.swift:572
	#3	0x00000001123c193d in AutomationTests.MyTests.beforeAll (AutomationTests.MyTests)() -> () at /Users/me/dev/myapp/MyApp/AutomationTests/MyTests.swift:45
	#4	0x0000000103fefc8c in __invoking___ ()
	#5	0x0000000103fefae2 in -[NSInvocation invoke] ()
	#6	0x00000001124990f7 in -[XCTestCase invokeTest] ()
	#7	0x00000001124992f8 in -[XCTestCase performTest:] ()
	#8	0x00000001124db866 in +[KIFTestCase performSetupTearDownWithSelector:] at /Users/me/dev/myapp/Pods/KIF/Classes/KIFTestCase.m:85
	#9	0x0000000112497f65 in -[XCTestSuite performTest:] ()
	#10	0x00000001124a2bf5 in -[XCTest run] ()
	#11	0x0000000112497ffb in -[XCTestSuite performTest:] ()
	#12	0x00000001124a2bf5 in -[XCTest run] ()
	#13	0x0000000112497ffb in -[XCTestSuite performTest:] ()
	#14	0x00000001124a2bf5 in -[XCTest run] ()
	#15	0x00000001124950bc in __25-[XCTestDriver _runSuite]_block_invoke ()
	#16	0x000000011249fead in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
	#17	0x0000000112494ff0 in -[XCTestDriver _runSuite] ()
	#18	0x0000000112495a1d in -[XCTestDriver _checkForTestManager] ()
	#19	0x00000001124a5af0 in +[XCTestProbe runTests:] ()
	#20	0x0000000103865d55 in __NSFireDelayedPerform ()
	#21	0x000000010405ff64 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
	#22	0x000000010405fb25 in __CFRunLoopDoTimer ()
	#23	0x0000000104022e5d in __CFRunLoopRun ()
	#24	0x0000000104022486 in CFRunLoopRunSpecific ()
	#25	0x0000000106e229f0 in GSEventRunModal ()
	#26	0x0000000104727420 in UIApplicationMain ()
	#27	0x0000000103159aee in top_level_code at /Users/me/dev/myapp/MyApp/AppDelegate.swift:20
	#28	0x0000000103159b2a in main ()
	#29	0x000000010a804145 in start ()

**Comment by TAKeanice** [comment]
What type is your `testUser.contactMethod`? If it is nil, the most recent fix on the master branch should solve the issue. I´ve tested with the following code:

```Swift
let people = swiftAddressBook?.allPeople
                
var phone = MultivalueEntry(value: "test", label: "mobile", id: 1)
                
people?.first?.phoneNumbers = [phone]
```

which works just fine (there are entries in the address book, I´m logging them afterwards, and the first one has the phonenumber "test"

**Comment by albertbori** [comment]
I tested the fix in master, and it solved #6, however it didn't solve this issue. I replaced `testUser.contactMethod` with `"test"` and it still fails. The biggest difference between your sample and my code, is that instead of grabbing the first contact, I'm trying to create a new contact:

    var person = SwiftAddressBookPerson.create()
    person.firstName = testUser.firstName
    person.lastName = testUser.lastName
    person.organization = testUser.companyName
    
    var phone = MultivalueEntry(value: "test", label: "mobile", id: 1)
    person.phoneNumbers = [phone]

    swiftAddressBook?.addRecord(person)

I'm probably doing this wrong, which is why I logged #8.

**Comment by TAKeanice** [comment]
That was more difficult than #8 . The old values were called on set and if they were nil, they were explicitly unwrapped by AddressBookFramework. Most recent version should fix it.

**Comment by albertbori** [comment]
Using master's latest commit, I'm still getting a `EXC_BAD_ACCESS` error in `setMultivalueProperty` still:

	Thread 1Queue : com.apple.main-thread (serial)
	#0	0x0000000110e3036a in ABMultiValueAddValueAndLabel ()
	#1	0x0000000107061262 in specialization <ObjectiveC.NSString with ObjectiveC.NSString : Swift.AnyObject> of SwiftAddressBook.SwiftAddressBookPerson.(setMultivalueProperty in _ECEF355CFD253D8039C191CB27BDAECD) (SwiftAddressBook.SwiftAddressBookPerson)<A : Swift.AnyObject>(Swift.Int32, Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<A>>>) -> () at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:710
	#2	0x0000000107048340 in specialization <Swift.String, ObjectiveC.NSString with ObjectiveC.NSString : Swift.AnyObject> of SwiftAddressBook.SwiftAddressBookPerson.(convertMultivalueEntries in _ECEF355CFD253D8039C191CB27BDAECD) (SwiftAddressBook.SwiftAddressBookPerson)<A, B : Swift.AnyObject>(Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<A>>>, converter : (A) -> B) -> Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<B>>> [inlined] at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:677
	#3	0x00000001070482c3 in SwiftAddressBook.SwiftAddressBookPerson.phoneNumbers.setter : Swift.Optional<Swift.Array<SwiftAddressBook.MultivalueEntry<Swift.String>>> at /Users/me/dev/SwiftAddressBook/Pod/Classes/SwiftAddressBookWrapper.swift:572
	#4	0x0000000115d23581 in AutomationTests.MyTests.beforeAll (AutomationTests.MyTests)() -> () at /Users/me/dev/myapp/MyApp/AutomationTests/MyTests.swift:44
	#5	0x0000000115d23ae2 in @objc AutomationTests.MyTests.beforeAll (AutomationTests.MyTests)() -> () ()
	#6	0x0000000107862c8c in __invoking___ ()
	#7	0x0000000107862ae2 in -[NSInvocation invoke] ()
	#8	0x0000000115e2e0f7 in -[XCTestCase invokeTest] ()
	#9	0x0000000115e2e2f8 in -[XCTestCase performTest:] ()
	#10	0x0000000115e712b1 in +[KIFTestCase performSetupTearDownWithSelector:] at /Users/me/dev/myapp/Pods/KIF/Classes/KIFTestCase.m:85
	#11	0x0000000115e71207 in +[KIFTestCase setUp] at /Users/me/dev/myapp/Pods/KIF/Classes/KIFTestCase.m:73
	#12	0x0000000115e2cf65 in -[XCTestSuite performTest:] ()
	#13	0x0000000115e37bf5 in -[XCTest run] ()
	#14	0x0000000115e2cffb in -[XCTestSuite performTest:] ()
	#15	0x0000000115e37bf5 in -[XCTest run] ()
	#16	0x0000000115e2cffb in -[XCTestSuite performTest:] ()
	#17	0x0000000115e37bf5 in -[XCTest run] ()
	#18	0x0000000115e2a0bc in __25-[XCTestDriver _runSuite]_block_invoke ()
	#19	0x0000000115e34ead in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
	#20	0x0000000115e29ff0 in -[XCTestDriver _runSuite] ()
	#21	0x0000000115e2aa1d in -[XCTestDriver _checkForTestManager] ()
	#22	0x0000000115e3aaf0 in +[XCTestProbe runTests:] ()
	#23	0x00000001071bcd55 in __NSFireDelayedPerform ()
	#24	0x00000001078d2f64 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
	#25	0x00000001078d2b25 in __CFRunLoopDoTimer ()
	#26	0x0000000107895e5d in __CFRunLoopRun ()
	#27	0x0000000107895486 in CFRunLoopRunSpecific ()
	#28	0x000000010a6959f0 in GSEventRunModal ()
	#29	0x0000000107f9a420 in UIApplicationMain ()
	#30	0x0000000106a377fe in top_level_code at /Users/me/dev/myapp/MyApp/AppDelegate.swift:20
	#31	0x0000000106a3783a in main ()
	#32	0x000000010e077145 in start ()
	#33	0x000000010e077145 in start ()

**Comment by TAKeanice** [comment]
Ok. I´ll continue testing tomorrow.

**Comment by TAKeanice** [comment]
```Swift
var person = SwiftAddressBookPerson.create()
                person.firstName = "newTestuserFirstname"
                person.lastName = "newTestuserLastname"
                person.organization = "newTestuserCompanyname"
                
                var phone = MultivalueEntry(value: "newTestuserNumber", label: "mobile", id: 1)
                person.phoneNumbers = [phone]
                
                swiftAddressBook?.addRecord(person)
```
succeeds

**Comment by TAKeanice** [comment]
Are you right now testing SwiftAddressBook as Pod? I am experiencing the crash only when using the wrapper as pod. Can you verify this and test the code when it´s not a pod?

**Comment by albertbori** [comment]
Testing with SwiftAddressBook copied into my solution, the code you posted [above](https://github.com/SocialbitGmbH/SwiftAddressBook/issues/9#issuecomment-74373693) does not throw an error, but `"newTestuserFirstname"` doesn't show up in the address book.

Testing with SwiftAddressBook as a Pod, I get the crash mentioned [here](https://github.com/SocialbitGmbH/SwiftAddressBook/issues/9#issuecomment-74282543). However, the crash happens inside of `setMultivalueProperty()`, and *not* inside of the method that I changed to fix the Pod compiling error: `convertMultivalueEntries`

It seems there is a different issue with Pod support that needs to be addressed. I'll keep looking into it.

**Comment by TAKeanice** [comment]
To see the contact, you first have to execute `save()` on swiftAddressBook. I tried another fix, which is highly illogical. I guess I just force the compiler not to optimize away some code from the pod, as during testing I discovered that `abmv` stayed nil even after initializing, and somehow skipped the if-clause after I tried one fix. Now that I´ve introduced a second variable and initialized that with abmv, then checking that for nil results in the correct execution. Can you try if changing a phone number from an existing contact and saving afterwards still works?

**Comment by albertbori** [comment]
It worked!!!

It appears that the AddressBook still needs a bit of polishing on Apple's side of things. Hopefully some of this will be fixed in Swift 1.2

**Comment by TAKeanice** [comment]
I´m not sure whether it´s about AddressBook or Swift. But anyhow, I think I can close that nasty bug now! :sunglasses: :thumbsup:

**Comment by albertbori** [comment]
Yea, it seems an issue similar to one I had working with the Keychain: https://github.com/matthewpalmer/Locksmith/issues/6#issuecomment-66380603

I think there are some run-time glitches that still need to be worked around here and there.

Thanks for the fix!

**Comment by TAKeanice** [comment]
Would be interesting to test whether the bug would appear with the old code, without compiler optimization. Also if the compilation error with the old implementation of `convertMultivalueEntries`, because that, too, seems to be only a failure of the compiler
